DROP SEQUENCE MYDRUG_SEQ;
DROP TABLE MYDRUG;

CREATE SEQUENCE MYDRUG_SEQ;

CREATE TABLE MYDRUG (
	MYDRUG_SEQ NUMBER NOT NULL,
	MEMBER_SEQ NUMBER NOT NULL,
	DRUG_CODE VARCHAR2(20) NOT NULL,
	MYDRUG_NAME VARCHAR2(1000) NOT NULL,
	MYDRUG_ABOUT VARCHAR2(1000) NOT NULL,
	MYDRUG_IMAGE VARCHAR2(2000) NOT NULL,
	MYDRUG_DATE DATE NOT NULL,
	
	CONSTRAINT MYDRUG_SEQ_PK PRIMARY KEY(MYDRUG_SEQ),
	CONSTRAINT MEMBER_SEQ_FK FOREIGN KEY(MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)
	
);

SELECT * FROM MYDRUG;

INSERT INTO MYDRUG
VALUES(MYDRUG_SEQ.NEXTVAL, 1, '1234', '약 이름', '약 설명', '약 이미지 경로', SYSDATE);

DELETE FROM MYDRUG
WHERE MYDRUG_SEQ = 3;