DROP TABLE MANAGE;
DROP SEQUENCE MANAGE_SEQ;

CREATE SEQUENCE MANAGE_SEQ;

CREATE TABLE MANAGE(
	MANAGE_SEQ NUMBER PRIMARY KEY NOT NULL, --일정번호 
	MEMBER_SEQ NUMBER REFERENCES MEMBER(MEMBER_SEQ) NOT NULL, --멤버고유번호
	TITLE VARCHAR2(50), --일정명
	START_DATE VARCHAR2(50), --일정시작날짜
	END_DATE VARCHAR2(50) --일정끝나는날짜
);

INSERT INTO MANAGE VALUES(MANAGE_SEQ.NEXTVAL, 1, '정형외과','2020-05-20','2020-05-24');

SELECT * FROM MANAGE;

DELETE FROM MANAGE WHERE MEMBER_SEQ = 1;

 